name: github pages ci cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Configure Git Author
        run: |
          git config --global user.email "leonargharib@gmail.com"
          git config --global user.name "LeoTheG"

      - name: deploy
        run: npm run deploy
